name: Docker Build and Publish

on:
  push:
    branches:
      - main
      - master
      - 'feature/*'
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        run: |
          git init
          git remote add origin http://sparsh:b16a297612aa45586373e2205dedeface87cd425@192.168.0.247:3002/sparsh/Directory-Organizer.git
          git fetch --depth=1 origin ${{ github.sha }}
          git reset --hard FETCH_HEAD

      - name: Log in to Gitea Container Registry
        run: |
          echo "b16a297612aa45586373e2205dedeface87cd425" | docker login 192.168.0.247:3002 -u "sparsh" --password-stdin
          echo "b16a297612aa45586373e2205dedeface87cd425" | docker login 127.0.0.1:3002 -u "sparsh" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t 192.168.0.247:3002/sparsh/directory-organizer:latest -t 127.0.0.1:3002/sparsh/directory-organizer:latest .

      - name: Push Docker image
        run: |
          docker push 192.168.0.247:3002/sparsh/directory-organizer:latest
          docker push 127.0.0.1:3002/sparsh/directory-organizer:latest
